Remove docker base for basic packaging bash + upload test result artifacts

diff --git a/.github/actions/package/action.yml b/.github/actions/package/action.yml
--- a/.github/actions/package/action.yml
+++ b/.github/actions/package/action.yml
@@ -7,13 +7,80 @@ inputs:
   is_snapshot:
     description: Whether or not this is a snapshot build
     required: true
-outputs:
-  artifact_path:
-    description: The path to the built zip file, relative to the workspace
-  artifact_remote_path:
-    description: Relative path for published artifact
-  artifact_name:
-    description: The file name of the built zip file
 runs:
-  using: 'docker'
-  image: 'Dockerfile'
+  using: 'composite'
+  steps:
+    - id: package
+      env:
+        RELEASE_VERSION: ${{ inputs.release_version }}
+        IS_SNAPSHOT: ${{ inputs.is_snapshot }}
+      run: |
+        ZIP_FILE_NAME="Preside-${RELEASE_VERSION/+/-}.zip"
+        NOW="`date`"
+
+        if [[ $RELEASE_VERSION == "0.0.0-DEMO"* ]] ; then
+          RELEASE_NAME="demo"
+        elif [[ "${IS_SNAPSHOT}" == "false" ]] ; then
+          RELEASE_NAME="stable"
+        else
+          RELEASE_NAME="bleeding-edge"
+        fi
+
+        echo "Packaging application ${RELEASE_VERSION}...";
+        echo "";
+        echo "";
+
+        PACKAGE_DIR="${GITHUB_WORKSPACE}/package"
+        ARTIFACTS_DIR="${GITHUB_WORKSPACE}/artifacts/${RELEASE_NAME}"
+        ZIP_FILE="${ARTIFACTS_DIR}/${ZIP_FILE_NAME}"
+
+        mkdir -p $PACKAGE_DIR
+        mkdir -p $ARTIFACTS_DIR
+
+        rsync -a ${GITHUB_WORKSPACE}/ --exclude=".*" --exclude="/package" --exclude="/artifacts" --exclude="*.sh" --exclude="/tests"  --exclude="/system/assets/node_modules" --exclude="zanata.xml" "$PACKAGE_DIR" || exit 1
+
+        cd $PACKAGE_DIR
+
+        echo "";
+        echo "Compiling static assets with grunt..."
+        echo "";
+
+        cd ./system/assets
+        npm install || exit 1
+        grunt all || exit 1
+
+        cd ../../
+
+        echo "";
+        echo "Setting up version files, etc..."
+        echo "";
+
+        echo '{ "version":"VERSION_NUMBER" }' > version.json
+        echo Built on: $NOW > "Preside-$RELEASE_VERSION-$RELEASE_NAME.txt"
+
+        mv box.json.published box.json
+
+        sed -i "s,VERSION_NUMBER,$RELEASE_VERSION," box.json
+        sed -i "s,VERSION_NUMBER,$RELEASE_VERSION," version.json
+        sed -i "s,VERSION_NUMBER,$RELEASE_VERSION," system/config/Config.cfc
+        sed -i "s,DOWNLOADLOCATION,$RELEASE_NAME\/${ZIP_FILE_NAME}," box.json
+
+        cp box.json ${GITHUB_WORKSPACE}/box.json
+
+        # CLEANUP
+        rm -rf ./system/externals/lucee-spreadsheet/javaLoader;
+        rm -rf ./system/externals/lucee-spreadsheet/test;
+        rm -rf ./system/externals/cfconcurrent/javaloader;
+
+        echo "";
+        echo "Zipping up project...";
+        echo "";
+
+        zip -rq $ZIP_FILE * -x jmimemagic.log || exit 1
+
+        echo "Uploading to https://downloads.preside.org/${RELEASE_NAME}/${ZIP_FILE_NAME} ..."
+        aws s3 cp --acl=public-read $ZIP_FILE s3://downloads.preside.org/${RELEASE_NAME}/${ZIP_FILE_NAME}
+
+        echo "";
+        echo "All done :)";
+        echo "";
